ALTER TABLE transactions
    ADD COLUMN IF NOT EXISTS transaction_value NUMERIC NOT NULL,
    ADD COLUMN IF NOT EXISTS ref_num TEXT NOT NULL,
    ADD COLUMN IF NOT EXISTS product TEXT NOT NULL,
    ADD COLUMN IF NOT EXISTS processed_year INTEGER NOT NULL,
    ADD COLUMN IF NOT EXISTS processed_month INTEGER NOT NULL,
    ADD COLUMN IF NOT EXISTS dmc_ib TEXT NOT NULL,
    ADD COLUMN IF NOT EXISTS dmc TEXT NOT NULL,
    ADD COLUMN IF NOT EXISTS partner_bank TEXT NOT NULL;